# Generated by Django 2.2.1 on 2019-07-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190702_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='date',
            new_name='datetime',
        ),
    ]
