# Generated by Django 2.2.1 on 2019-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190708_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
    ]
