# Generated by Django 2.2.1 on 2019-07-08 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190708_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledupdate',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 7, 44, 7, 736053, tzinfo=utc), verbose_name='Дата обновления'),
        ),
    ]
